language: rust
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+(-\\w*)?$/"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly
      script:
        - cargo test
    - rust: beta
      script:
        - cargo test
    - rust: stable
      install:
        - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
      env:
        - RUSTFLAGS="-D warnings"
      script:
        - cargo fmt -- --check
        - cargo test
        - cargo build
        - cargo doc
        - cargo package
      deploy:
        provider: cargo
        on:
          branch: master
          tags: true
        token:
          secure: btf1djD7Bt5cZzqL/0zPD3TgwppJv2UmpbCJrfD0NNNADs89u/5C4GsF1mjufbOa0bKn/I05DZsL+Gn0xyzJNMdT4vcCkXO9pb0KNSbcSQHr28rl9CdnlFALmk1AgFH1QEpatVmniTxF1uqeMpjng0HHEvDaExLbjpW9nA4XeniLIFqAlfY/u9f+ASdXLSS0dTgdGO7oss7LmIrbDObbIcOansYCoYaemsr3lek10+NDE92PnwBaDdhoa8plTN7Wo1IvZAm1a23NhKA9Nyab4jVQRbzkL9zv9M2RKavanq4fAryRZr1C/KfDjb7JHyYvZMICUk59MlIeKPEB7XBqm25zmxP9J8rNaf7LFzO/8DDk2g/o1yF+D8ykLv6KWlts3SaBtXjHDC76jUDZNDDPH09KMq/YYpv7E6WI1fkFk1HAHpLeCkX/JAsAdj2HQunwDMqSKCsw2mxoYVcWYtAj6Ja686C9rOB5o9mx6oiRzPAI69QzUZXpMEaVMJT2z/jBbkmJiN9ps7eaGf88NaFWi2B+Am/vuh6YLKsVAzgXamGMGOChwuUstz9GeYTue6JT1UrO4gtivVJ2WHIW7eZjeaLMJZyfKh3yBJzzMQilowSlwnaadgodl5Xxkhj5cF8NEVIRJOwhROW+sapQePVoSzEaALijI3U5x9MsBYYSJuw=
