language: rust
notifications:
  email:
    on_success: never
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+(-\\w*)?$/"
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - rust: nightly
    script:
    - cargo test
  - rust: beta
    script:
    - cargo test
  - rust: stable
    install:
    - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
    env:
    - RUSTFLAGS="-D warnings"
    script:
    - cargo fmt -- --check
    - cargo test
    - cargo build
    - cargo doc
    - cargo package
    deploy:
      provider: cargo
      on:
        branch: master
        tags: true
      token:
        secure: qn/U7SQF+Ho7/CcVbJOAD+t1h5AKIl8kdOHA6dJQ8LCbm2AC/luzjbRwO773qoLJicp4PyA8MgfVgAF4nM5bYbxqMG69+vI3VfnzkEpJr1yMVaVUfOv3LPoP37GXBmRbFcKMPwmUZsU8wDxY8jpMa+l5G1ngKFbkg38m6dFWwxPy7D15lbzkBzCknnArGorhTsqzx73zpEsNgET59q/2begvuXWOtpAeuGiRsJwZfRkT7f798pRfBksqkqYSp2AgOhG48nBUWABQDLc5pvQzuvH9NMv0sLl5aKsg2ShWPWcHaJvzW92x6XISXJkh70H8llDN3E7FM5+wSn4Y+5At+eIMMCUbNuBHms/nNxfKTJuVvVwnv5u40uU0uqskMJ6sUBl0SjPYV6CI5yidXDBfIVd5Egx6QhRykRE5nu+pgiubrTUR3KhWbuCnYOXGJQ250YEMAws8F4y308Fhr/inXX6u/n9aOt7qn3aJkTAAfrRVW4Pob2qtJDRgIAx746+leVHsNTGwWDrGIcUoHc9bgC7x9ZDTqncvhpArHoPJIO/f7fOESVhRNfh2yoZEgFrZtRc2dcK+AaSx6Y0vEbAp/TlzLJPEUYNXtqP6Uz8E+tdwCbcVARnShR0VSe/nd6oECEWOS4jl9jtvdliIHYCnWPGjt9zZTNEsFpcGCfltfgE=
