language: rust
notifications:
  email:
    on_success: never
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+(-\\w*)?$/"
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - rust: nightly
    script:
    - cargo test
  - rust: beta
    script:
    - cargo test
  - rust: stable
    install:
    - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
    env:
    - RUSTFLAGS="-D warnings"
    script:
    - cargo fmt -- --check
    - cargo test
    - cargo build
    - cargo doc
    - cargo package
    deploy:
      provider: cargo
      on:
        branch: master
        tags: true
      token:
        secure: Q4Y7/4xw3mNMzK//0LjPi3rLLGzOSVxZsCp0QFaDqdk5RS++j6X4DKD8blGJj5Qb4WUMSSzPp2nTFUpjnSU9PcQKvXfPTPnkYUCeZOBsPACbTA7XI5SCr6ApE4aVDEtBG6YTUByEPE01EGNsiUNrPns/ccpOd4qxE9l/hJLNM1u9BiwCqMiIb75R0s/W/fl3U3m/Ki4yLd6FkVH8q/IAXyyNQa4r/g2d7COTbC05l4WeOc+m4NJ6EQICLnPm2Gz3pbIIp5tJG+aefIRPnvdRjYq6nxQQNNtKuRoDnrRR77AITupT813PNkkgKXZj7w7RGSueZMg2v7DIT1ik2p6YIC8mTuUKEoOABuqsHc5+InMKdNa1ZnlBg0TggBEtx4psEgxqiF0GQ9eWJD7EJ9N9FwD3FGFjJKNpCxYl8SalshZBnIwMEfsa92patFHINa+4b6cCfMmG6fL7WC+9Q2LumJ9f+MUJqznBET6IxBx/WpS4iW5t2s6PkCnQqKIrhl1tIzTmf1xq768UdtngK/MbbUumLr+OwXMP06lVvGmZSS1exIVV/KQ2S0Pcb3oI1pTvn9lBWHnTzUApZ5HyxPOZo++wuxN/yy8Sj01flzpT2DAgoK95uQQR4mq2n9VAv6hU0KNrY7Tjmd9zYTcHCBNZx0wqRW1ItB7G8DK6xqnsJTw=
